# Generated by Django 4.1.2 on 2022-10-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_last_name_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
