# Generated by Django 4.1.1 on 2022-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_categories_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('Dress', 'Dress'), ('Suits', 'Suits'), ('Trouser', 'Trouser'), ('Gowns', 'Gowns')], max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='kids',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='men',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='women',
            field=models.ImageField(upload_to=''),
        ),
    ]
