# Generated by Django 4.1.1 on 2022-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cloth_alter_category_kids_alter_category_men_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
