# Generated by Django 4.1.2 on 2022-10-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_size', models.ImageField(upload_to='')),
                ('plump', models.ImageField(upload_to='')),
                ('ptriangle', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.TextField()),
                ('newarrivals', models.TextField()),
                ('men', models.TextField()),
                ('women', models.TextField()),
                ('kids', models.TextField()),
                ('mostpopular', models.TextField()),
                ('prices', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=10)),
                ('profile', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=10)),
                ('order_on', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_on', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=10)),
                ('measurement', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=10)),
                ('material', models.CharField(blank=True, max_length=10)),
                ('occasion', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
