# Generated by Django 4.1.2 on 2022-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ImageField(upload_to='pictures/')),
                ('men', models.ImageField(upload_to='pictures/')),
                ('women', models.ImageField(upload_to='pictures/')),
                ('kids', models.ImageField(upload_to='pictures/')),
                ('mostpopular', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ImageField(upload_to='')),
                ('shirts', models.ImageField(upload_to='')),
                ('jackets', models.ImageField(upload_to='')),
                ('dress', models.ImageField(upload_to='')),
                ('suits', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ImageField(upload_to='')),
                ('shirts', models.ImageField(upload_to='')),
                ('jackets', models.ImageField(upload_to='')),
                ('suits', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ImageField(upload_to='')),
                ('shirts', models.ImageField(upload_to='')),
                ('jackets', models.ImageField(upload_to='')),
                ('dress', models.ImageField(upload_to='')),
                ('skirts', models.ImageField(upload_to='')),
            ],
        ),
    ]
