# Generated by Django 4.1.2 on 2022-10-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('men', 'men'), ('women', 'women'), ('kids', 'kids'), ('mostpopular', 'mostpopular')], max_length=200, null=True),
        ),
    ]
