# Generated by Django 4.1.2 on 2022-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmPassword',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
