# Generated by Django 4.1.2 on 2022-10-24 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_size', models.ImageField(upload_to='')),
                ('plump', models.ImageField(upload_to='')),
                ('ptriangle', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.TextField()),
                ('newarrivals', models.TextField()),
                ('men', models.ImageField(upload_to='')),
                ('women', models.ImageField(upload_to='')),
                ('kids', models.ImageField(upload_to='')),
                ('mostpopular', models.TextField()),
                ('prices', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('type', models.CharField(choices=[('dress', 'dress'), ('suits', 'suits'), ('trouser', 'trouser'), ('gowns', 'gowns')], max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='SOME STRING', max_length=10, null=True)),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=10)),
                ('measurement', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=10)),
                ('material', models.CharField(blank=True, max_length=10)),
                ('occasion', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
