# Generated by Django 4.1.2 on 2022-10-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=10)),
                ("profile", models.ImageField(upload_to="")),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(name="Customer",),
    ]
