# Generated by Django 4.1.2 on 2022-11-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
