# Generated by Django 4.1.2 on 2022-11-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmPassword',
        ),
    ]
