# Generated by Django 4.1.2 on 2022-10-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kids_wearer_men_wearer_women_wearer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kids',
            name='wearer',
        ),
        migrations.RemoveField(
            model_name='men',
            name='wearer',
        ),
        migrations.RemoveField(
            model_name='women',
            name='wearer',
        ),
    ]
