# Generated by Django 4.1.2 on 2022-11-03 06:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pictures'),
        ),
        migrations.AlterField(
            model_name='kids',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pictures'),
        ),
        migrations.AlterField(
            model_name='men',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pictures'),
        ),
        migrations.AlterField(
            model_name='women',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pictures'),
        ),
    ]
