# Generated by Django 4.1.2 on 2022-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_kids_wearer_remove_men_wearer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='wearer',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='men',
            name='wearer',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='wearer',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='SOME STRING', max_length=10, null=True),
        ),
    ]
