# Generated by Django 4.1.2 on 2022-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kids_wearer_men_wearer_women_wearer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('dress', 'dress'), ('skirts', 'skirts'), ('trouser', 'trouser'), ('shirts', 'shirts')], max_length=100, null=True),
        ),
    ]
