# Generated by Django 4.1.2 on 2022-10-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_categories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('dress', 'dress'), ('skirts', 'skirts'), ('trouser', 'trouser'), ('shirts', 'shirts')], max_length=200, null=True),
        ),
    ]
