# Generated by Django 4.1.2 on 2022-10-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_categories_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kids',
        ),
    ]
