# Generated by Django 4.1.2 on 2022-10-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_kids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
