# Generated by Django 4.1.2 on 2022-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categories_wearer_kids_wearer_men_wearer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('dress', 'dress'), ('trouser', 'trouser'), ('shirts', 'shirts')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kids',
            name='type',
            field=models.CharField(choices=[('dress', 'dress'), ('trouser', 'trouser'), ('shirts', 'shirts')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='type',
            field=models.CharField(choices=[('dress', 'dress'), ('trouser', 'trouser'), ('shirts', 'shirts')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='type',
            field=models.CharField(choices=[('dress', 'dress'), ('trouser', 'trouser'), ('shirts', 'shirts')], max_length=10, null=True),
        ),
    ]
