# Generated by Django 4.1 on 2022-10-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ImageField(upload_to='')),
                ('men', models.ImageField(upload_to='')),
                ('women', models.ImageField(upload_to='')),
                ('kids', models.ImageField(upload_to='')),
                ('mostpopular', models.ImageField(upload_to='')),
                ('prices', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ImageField(upload_to='')),
                ('shirts', models.ImageField(upload_to='')),
                ('jackets', models.ImageField(upload_to='')),
                ('dress', models.ImageField(upload_to='')),
                ('suits', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ImageField(upload_to='')),
                ('shirts', models.ImageField(upload_to='')),
                ('jackets', models.ImageField(upload_to='')),
                ('suits', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ImageField(upload_to='')),
                ('shirts', models.ImageField(upload_to='')),
                ('jackets', models.ImageField(upload_to='')),
                ('dress', models.ImageField(upload_to='')),
                ('suits', models.ImageField(upload_to='')),
            ],
        ),
    ]
