# Generated by Django 4.1.2 on 2022-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=10)),
                ('measurement', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=10)),
                ('material', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
        migrations.RenameField(
            model_name='bodytype',
            old_name='ptriangle',
            new_name='triangle',
        ),
    ]
