# Generated by Django 4.1 on 2022-10-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0002_categories_kids_men_women'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
