# Generated by Django 4.1 on 2022-10-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0003_rename_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
