# Generated by Django 4.1.2 on 2022-10-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0004_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ImageField(upload_to='')),
                ('men', models.ImageField(upload_to='')),
                ('women', models.ImageField(upload_to='')),
                ('kids', models.ImageField(upload_to='')),
                ('mostpopular', models.ImageField(upload_to='')),
                ('prices', models.CharField(max_length=10)),
            ],
        ),
    ]
