# Generated by Django 4.1 on 2022-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0006_remove_categories_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='kids',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='men',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='mostpopular',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='new',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='women',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
