# Generated by Django 4.1.2 on 2022-10-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0007_alter_categories_kids_alter_categories_men_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='suits',
            new_name='skirts',
        ),
    ]
