# Generated by Django 4.1.2 on 2022-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asili', '0008_rename_suits_women_skirts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
